package com.ibl.tool.clapfindphone


// sound type
const val DEFAULT_SOUND_TYPE = 4928
const val IMPORT_SOUND_TYPE = 8490
const val ADS_SOUND_TYPE = 6544
const val CREATE_SOUND_TYPE = 6549

//adapter item type
const val ADAPTER_ITEM_TYPE = 4809
const val ADAPTER_ADS_TYPE = 9584

//adapter key
const val KEY_SOUND = "KEY_SOUND_JDK"

//intent key
const val KEY_SOUND_ITEM_DATA = "KEY_SOUND_ITEM_DATA_JDK"
//intent action
const val ACTION_VOLUME_CHANGED: String = "android.media.VOLUME_CHANGED_ACTION"
const val ACTION_NOTIFICATION_CLICKED_SERVICE = "ACTION_NOTIFICATION_CLICKED_JDK"

//vibrate
const val MODE_VIBRATE_DEFAULT = 1232
const val MODE_VIBRATE_STRONG = 1233
const val MODE_VIBRATE_HEART = 1235
const val MODE_VIBRATE_TICKTOCK = 1236

//flash
const val MODE_FLASH_DEFAULT = 12342
const val MODE_FLASH_DISCO = 12343
const val MODE_FLASH_SOS = 12344

//settings key
const val KEY_HAS_SOUND = "KEY_HAS_SOUND"
const val KEY_HAS_FLASH = "KEY_HAS_FLASH"
const val KEY_HAS_VIBRATE = "KEY_HAS_VIBRATE"

//permission
const val REQUEST_PERMISSION_CODE = 14312
const val REQUEST_READ_PERMISSION_CODE = 14313
const val REQUEST_MICRO_PERMISSION_CODE = 14314
const val REQUEST_NOTIFICATION_PERMISSION_CODE = 14317
const val REQUEST_READ_AUDIO_PERMISSION_CODE = 14316

//file dir
const val DIRECTION_AUDIO_CACHE_NAME = "find_my_phone_audio"

//broadcast intent action
const val ACTION_UPDATE_AUDIO_IMPORT = "ACTION_UPDATE_AUDIO_IMPORT_JDK"
const val ACTION_FINISH_CREATE_SOUND_SCREEN = "ACTION_FINISH_CREATE_SOUND_SCREEN_JDK"
const val ACTION_FINISH_DETECT = "ACTION_FINISH_DETECT_JDK"

//request intent data
const val REQUEST_FILE_AUDIO_CODE = 4328

//sound apply
const val KEY_SOUND_APPLY = "KEY_SOUND_APPLY_JDK"


//key appPreferences
const val KEY_CURRENT_DURATION = "KEY_CURRENT_DURATION_JDK"
const val KEY_CURRENT_VOLUME = "KEY_CURRENT_VOLUME_JDK"
const val KEY_CURRENT_LANGUAGE = "KEY_CURRENT_LANGUAGE_JDK"
const val KEY_CURRENT_IDX_LANGUAGE = "KEY_CURRENT_IDX_LANGUAGE_JDK"
const val KEY_CHOOSE_LANGUAGE = "KEY_CHOOSE_LANGUAGE_JDK"
const val KEY_HAS_SELECTED_SOUND = "KEY_HAS_SELECTED_SOUND_JDK"